language: php
php:
  - 7
addons:
  apt_packages:
      - php-curl
      - php-openssl
before_script:
  - openssl version -v
  - curl -V
  - composer self-update
  - composer update --no-interaction --prefer-dist
script:
  - vendor/bin/phpcs module/