language: php
php:
  - 7
addons:
  apt:
    pacages:
    - g++-4.9
    - libstdc++-4.9-dev
    - autoconf
    - automake
    - autotools-dev
    - libtool
    - pkg-config
    - zlib1g-dev
    - libcunit1-dev
    - libssl-dev
    - libxml2-dev
    - libev-dev
    - libevent-dev
    - libjansson-dev
    - libjemalloc-dev
    - libc-ares-dev
    - cmake
    - cmake-data
before_script:
#  - wget https://www.openssl.org/source/openssl-1.0.2g.tar.gz
#  - tar -xzvf openssl-1.0.2g.tar.gz
#  - cd openssl-1.0.2g
##  - sudo ./config
#  - sudo ./config enable-shared
#  - make
#  - sudo make install
#  - sudo ln -sf /usr/local/ssl/bin/openssl /usr/bin/openssl
#
#  - git clone https://github.com/tatsuhiro-t/nghttp2.git
#  - cd nghttp2
#  - autoreconf -i
#  - automake
#  - autoconf
#  - ./configure
#  - make
#  - sudo make install
#
#  - cd ~
#  - sudo apt-get build-dep curl
#  - wget http://curl.haxx.se/download/curl-7.46.0.tar.bz2
#  - tar -xvjf curl-7.46.0.tar.bz2
#  - cd curl-7.46.0
##  - ./configure --with-nghttp2=/usr/local --with-openssl=/usr/bin/openssl
#  - ./configure --with-nghttp2=/usr/local --with-openssl=/usr/bin/ssl
#  - make
#  - sudo make install
#  - sudo ldconfig

  - sudo apt-get install software-properties-common python-software-properties
  - sudo add-apt-repository -y ppa:ondrej/php-7.0
  -
  - sudo apt-get update
#  - sudo apt-get install php7.0-curl
#  - sudo apt-get install libssl1.0.2


  - sudo apt-get purge php5-fpm
  - sudo apt-get install php7.0-cli php7.0-common libapache2-mod-php7.0 php7.0 php7.0-mysql php7.0-fpm php7.0-curl php7.0-gd php7.0-bz2

  - ls /etc/php/7.0
#  - ls /etc/php/7.0/cli/conf.d

  - sudo echo extension=curl.so >> /etc/php/7.0/cli/conf.d/20-curl.ini

  - php -i | grep OpenSSL
  - php -i | grep curl

#  - openssl version -a
#  - curl -V
#  - cd /home/travis/build/KeithChasen/Phpushios
  - composer install
script:
  - vendor/bin/phpcs module/